export const SET_SCORES_DATA = 'SET_SCORES_DATA';
export const SET_CURRENT_SCORE = 'SET_CURRENT_SCORE';
export const SAVE_NEW_SCORE = 'SAVE_NEW_SCORE';
export const SAVE_CURRENT_SCORE = 'SAVE_CURRENT_SCORE';
