export const GET_QUIZ_DATA_REQUEST = 'GET_QUIZ_DATA_REQUEST';
export const GET_QUIZ_DATA_SUCCESS = 'GET_QUIZ_DATA_SUCCESS';
export const GET_QUIZ_DATA_FAILURE = 'GET_QUIZ_DATA_FAILURE';

export const SET_QUIZ_DATA = 'SET_QUIZ_DATA';
export const SET_QUESTION_ANSWERS = 'SET_QUESTION_ANSWERS';
